# Generated by Django 4.0.5 on 2022-06-25 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='current_users',
        ),
        migrations.RemoveField(
            model_name='room',
            name='host',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
